# Font settings
FONT_FAMILY = "Arial"
FONT_HEADLINE = (FONT_FAMILY, 32, "bold")
FONT_TITLE = (FONT_FAMILY, 24, "bold")
FONT_SUBTITLE = (FONT_FAMILY, 16)
FONT_BODY = (FONT_FAMILY, 14)
FONT_BUTTON = (FONT_FAMILY, 14, "bold")
FONT_CAPTION = (FONT_FAMILY, 12)

# Color settings
COLOR_PRIMARY = "#4592D0"
COLOR_SECONDARY = "#03DAC6"
COLOR_BACKGROUND = "#2b2b2b"
COLOR_SURFACE = "#242424"
COLOR_TEXT = "#FFFFFF"
COLOR_TEXT_SECONDARY = "#A1A1A1"

# Spacing and sizes
SPACING_SMALL = 4
SPACING_MEDIUM = 8
SPACING_LARGE = 16
BUTTON_HEIGHT = 36
BUTTON_WIDTH = 88
INPUT_HEIGHT = 56
